# Katarzyna Zaleska
# WCY19IJ1S1

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationWindow(object):
    def setupUi(self, AuthorizationWindow):
        AuthorizationWindow.setObjectName("AuthorizationWindow")
        AuthorizationWindow.resize(388, 459)
        AuthorizationWindow.setMinimumSize(QtCore.QSize(388, 459))
        AuthorizationWindow.setMaximumSize(QtCore.QSize(388, 459))
        AuthorizationWindow.setStatusTip("")
        AuthorizationWindow.setStyleSheet("QDialog {\n"
"background-color: #2a292e;\n"
"}\n"
"QLabel {\n"
"color: #1db954;\n"
"font-size: 18px;\n"
"}\n"
"QLineEdit {\n"
"font-size: 18px;\n"
"}")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(AuthorizationWindow)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(AuthorizationWindow)
        self.label_3.setStyleSheet("font-weight: bold;\n"
"font-size: 24px;\n"
"line-height: 2;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 45)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(AuthorizationWindow)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.entered_client_id = QtWidgets.QLineEdit(AuthorizationWindow)
        self.entered_client_id.setObjectName("entered_client_id")
        self.verticalLayout_4.addWidget(self.entered_client_id)
        self.label_2 = QtWidgets.QLabel(AuthorizationWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.entered_client_secret = QtWidgets.QLineEdit(AuthorizationWindow)
        self.entered_client_secret.setInputMask("")
        self.entered_client_secret.setText("")
        self.entered_client_secret.setEchoMode(QtWidgets.QLineEdit.Password)
        self.entered_client_secret.setReadOnly(False)
        self.entered_client_secret.setObjectName("entered_client_secret")
        self.verticalLayout_4.addWidget(self.entered_client_secret)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.submit_msg = QtWidgets.QLabel(AuthorizationWindow)
        self.submit_msg.setText("")
        self.submit_msg.setObjectName("submit_msg")
        self.verticalLayout_4.addWidget(self.submit_msg)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.submit_btn = QtWidgets.QPushButton(AuthorizationWindow)
        self.submit_btn.setMinimumSize(QtCore.QSize(150, 44))
        self.submit_btn.setMaximumSize(QtCore.QSize(170, 44))
        self.submit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submit_btn.setStyleSheet("QPushButton{\n"
"font-size: 18px;\n"
"font-weight: bold;\n"
"color: #1db954;\n"
"border: 2px solid #1db954;\n"
"border-radius: 14px;\n"
"letter-spacing: 1px;\n"
"}\n"
"QPushButton:hover {\n"
"color: #121212;\n"
"background-color:     #1db954;\n"
"border: 2px solid #121212;\n"
"}")
        self.submit_btn.setObjectName("submit_btn")
        self.verticalLayout_4.addWidget(self.submit_btn, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout)

        self.retranslateUi(AuthorizationWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationWindow)

    def retranslateUi(self, AuthorizationWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationWindow.setWindowTitle(_translate("AuthorizationWindow", "Authorization"))
        self.label_3.setText(_translate("AuthorizationWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Authorization</span></p></body></html>"))
        self.label.setText(_translate("AuthorizationWindow", "Client ID"))
        self.label_2.setText(_translate("AuthorizationWindow", "Client secret"))
        self.submit_btn.setText(_translate("AuthorizationWindow", "SUBMIT"))
